---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu, update cache
    apt:
      name:
        - apache2
        - librapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for CentOS , update cache
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
