---

- hosts: all
  become: true
  tasks:

  - name: update repo cache (CentOS)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHDtykfolDV7BuaU9RP/w3G4YShHYuIsw4QcHdBuWLB0 ansible2"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu, update cache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"


  - name: install apache and php packages for CentOS , update cache
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644



- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb packages for Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb for CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba  packages
    package:
      name: samba
      state: latest
